-- Create master and tenant schemas
CREATE SCHEMA IF NOT EXISTS MASTER AUTHORIZATION james_bond;
CREATE SCHEMA IF NOT EXISTS TENANT_ACME AUTHORIZATION james_bond;
CREATE SCHEMA IF NOT EXISTS TENANT_ARGUS AUTHORIZATION james_bond;

-- Tables for master schema
CREATE TABLE IF NOT EXISTS MASTER.TENANT_INFO(
  TENANT_NAME VARCHAR(32) NOT NULL PRIMARY KEY,
  TENANT_SCHEMA VARCHAR(32) NOT NULL
);

-- Tables for tenant schemas
CREATE TABLE IF NOT EXISTS TENANT_ACME.ORGANIZATION(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS TENANT_ARGUS.ORGANIZATION(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(64)
);